# Generated by Django 6.0.1 on 2026-03-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Заметка')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from_links', to='shop.product', verbose_name='Товар')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_links', to='shop.product', verbose_name='Похожий на')),
            ],
            options={
                'verbose_name': 'Похожий товар',
                'verbose_name_plural': 'Похожие товары',
                'unique_together': {('from_product', 'to_product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_reverse', through='shop.ProductSimilar', through_fields=('from_product', 'to_product'), to='shop.product', verbose_name='Похожие товары'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='shop.product', verbose_name='Товар')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='shop.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег товара',
                'verbose_name_plural': 'Теги товаров',
                'ordering': ['sort_order', 'pk'],
                'unique_together': {('product', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', through='shop.ProductTag', to='shop.tag', verbose_name='Теги'),
        ),
    ]
