# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_lab4_tags_and_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='shop/covers/',
                verbose_name='Фото (загрузка файла)',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='shop/specs/',
                verbose_name='Файл спецификации (PDF и др.)',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='shop/tags/',
                verbose_name='Иконка',
            ),
        ),
    ]
