# Generated by Django 6.0.1 on 2026-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_lab5_files_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab6Scratch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Метка')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка (URLField)')),
                ('counter', models.IntegerField(default=0, verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Лаба 6 (scratch)',
                'verbose_name_plural': 'Лаба 6 (scratch)',
            },
        ),
    ]
